In [2]:
import sys
import sys
sys.executable

'/home/iid/miniconda3/envs/pytorch_env/bin/python'

In [3]:
!conda install pandas  -y


2 channel Terms of Service accepted
Channels:
 - defaults
Platform: linux-64
Solving environment: done


==> WARNING: A newer version of conda exists. <==
    current version: 25.11.1
    latest version: 26.1.1

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /home/iid/miniconda3/envs/pytorch_env

  added / updated specs:
    - pandas


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    mkl-service-2.5.2          |  py311hacdc0fc_0          74 KB
    mkl_fft-2.1.1              |  py311h8fe796d_0         176 KB
    mkl_random-1.3.0           |  py311h505adc9_0         317 KB
    numpy-2.4.2                |  py311h08c6c3d_0          20 KB
    numpy-base-2.4.2           |  py311h00548fb_0         8.7 MB
    pandas-3.0.0               |  py311h86c3e14_0        14.2 MB
    python-dateutil-2.9.0post0 |  py311h06a4308_2  

In [58]:
import  pandas
print(sys.version)
!conda install matplotlib -y

3.11.13 (main, Jun  5 2025, 13:12:00) [GCC 11.2.0]
2 channel Terms of Service accepted
Channels:
 - defaults
Platform: linux-64
Solving environment: done


==> WARNING: A newer version of conda exists. <==
    current version: 25.5.1
    latest version: 25.11.1

Please update conda by running

    $ conda update -n base -c defaults conda



# All requested packages already installed.



In [59]:
import pandas as pd
import torch
import numpy  as np
import  matplotlib.pyplot as plt
import matplotlib

print("Pandas version:", pd.__version__)

# Check version of torch (PyTorch)
print("PyTorch version:", torch.__version__)

# Check version of numpy
print("Numpy version:", np.__version__)

# Check version of matplotlib
print("Matplotlib version:", matplotlib.__version__)
print(sys.version)

tensor_1d = torch.tensor([1, 2, 3])
print("1D Tensor (Vector):")
print(tensor_1d)
print()

Pandas version: 2.3.3
PyTorch version: 2.7.0+cpu
Numpy version: 2.3.4
Matplotlib version: 3.10.6
3.11.13 (main, Jun  5 2025, 13:12:00) [GCC 11.2.0]
1D Tensor (Vector):
tensor([1, 2, 3])



In [60]:
!pip install jupyter_contrib_nbextensions 

In [61]:
#Indroduction to the tensor 

In [62]:
import torch
scaler=torch.tensor(7)
scaler

tensor(7)

In [63]:
scaler2=torch.tensor(1)
scaler2

tensor(1)

In [64]:
#creating the 2d tensor 

In [65]:
twdtensor = torch.tensor([[1, 1], [2, 2]])
twdtensor

tensor([[1, 1],
        [2, 2]])

In [66]:
#creating the 3d tensor



In [67]:
d3tensor=torch.tensor([[[1,2]],[[3,4]]])
d3tensor

tensor([[[1, 2]],

        [[3, 4]]])

In [68]:
d3tensor.ndim  #it give the dimension

3

In [69]:
d3tensor[0]   #get the tensor as int
d3tensor[1][0][1]   #get the tensor as int

tensor(4)

In [70]:
#introduction to matrix

In [71]:
matrix=torch.tensor([[1,2],[3,4]])
print(matrix)

tensor([[1, 2],
        [3, 4]])


In [72]:
matrix.ndim

2

In [73]:
matrix.shape

torch.Size([2, 2])

In [74]:
tensor2=torch.tensor([[1,2],[3,4]])

tensor2

tensor([[1, 2],
        [3, 4]])

In [75]:
tensor2.shape

torch.Size([2, 2])

#Rnadom tensor
torch.rand(*size, *, generator=None, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False, 
           pin_memory=False) → Tensor



# https://www.learnpytorch.io/02_pytorch_classification/

# start with random number->look at data ->update random number->look at data -> update random number  neural network works like this

In [81]:
x = torch.rand([3, 4])   # 3 rows, 4 columns
print(x)
print(x.size())
print(x[0])



tensor([[0.3939, 0.7477, 0.3276, 0.0019],
        [0.1422, 0.1140, 0.6861, 0.9399],
        [0.7074, 0.6402, 0.2735, 0.9295]])
torch.Size([3, 4])
tensor([0.3939, 0.7477, 0.3276, 0.0019])


In [82]:
x.ndim

2

# create a random tensor similiar to image dimension  height and width and color channel(red,blue and green)

In [83]:
image_rand_tensor=torch.rand(224,224,3)
print(image_rand_tensor)

tensor([[[0.4615, 0.7122, 0.4297],
         [0.9396, 0.3957, 0.2143],
         [0.3138, 0.5707, 0.9255],
         ...,
         [0.6108, 0.1947, 0.6902],
         [0.8802, 0.5486, 0.0485],
         [0.6172, 0.6469, 0.1558]],

        [[0.2542, 0.3037, 0.7537],
         [0.4811, 0.8133, 0.6929],
         [0.3249, 0.8721, 0.7049],
         ...,
         [0.6508, 0.2554, 0.5129],
         [0.2341, 0.2345, 0.8737],
         [0.3342, 0.4053, 0.8305]],

        [[0.1576, 0.2114, 0.9038],
         [0.8896, 0.2587, 0.8294],
         [0.1806, 0.6507, 0.9429],
         ...,
         [0.4780, 0.0449, 0.2292],
         [0.2128, 0.4913, 0.0171],
         [0.3871, 0.7040, 0.5828]],

        ...,

        [[0.6137, 0.2598, 0.5337],
         [0.7106, 0.1354, 0.2185],
         [0.2082, 0.7880, 0.7378],
         ...,
         [0.6740, 0.6143, 0.2059],
         [0.7650, 0.7659, 0.8660],
         [0.7540, 0.9375, 0.0137]],

        [[0.9521, 0.9567, 0.8159],
         [0.4018, 0.5663, 0.8789],
         [0.

In [1]:
image_rand_tensor.shape,image_rand_tensor.ndim

NameError: name 'image_rand_tensor' is not defined